server:
  port: 8890

spring:
  config:
    import: secret/application-secret.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: contract-service
  datasource:
    url: jdbc:mariadb://3.38.213.43:3306/contractdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zmffkdnxm409!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost} # 외부에서 접근 가능한 호스트 이름 또는 IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka.clouter.kr/eureka


#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${eureka.instance.hostname:localhost}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: https://eureka.clouter.kr/eureka

jwt:
  secret: VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=VGhpcyBpcyBhIGRlbW8gcHJvamVjdCBmb3IgaW1wbGVtZW50aW5nIGp3dC4=
  refresh-token-validity-in-seconds: 1209600 # 14?
  access-token-validity-in-seconds: 43200 # 12??

springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
