server:
  port: 8889

spring:
  config:
    import: secret/application-secret.yml
  application:
    name: advertisement-service
  datasource:
    url: jdbc:mariadb://3.38.213.43:3306/advertisementdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zmffkdnxm409!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost} # 외부에서 접근 가능한 호스트 이름 또는 IP
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka.clouter.kr/eureka